# build environment
FROM node:15-alpine as build
WORKDIR /home/node
COPY . ./
RUN NODE_OPTIONS=--max_old_space_size=1000; npm ci
RUN npm run build
ENTRYPOINT ["npm", "start"]

# prod environment
FROM nginx:stable-alpine
COPY --from=build /home/node/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
