pipeline {
    agent {
        kubernetes {
            inheritFrom 'jenkins-agent'
            yaml '''
                  containers:
                  - name: docker
                    image: docker:dind
                    command:
                    - cat
                    tty: true
                '''
        }
    }

    stages {
        stage('Build Docker images') {
            steps {
                dir('react-frontend') {
                    sh "docker info"
                }
            }
        }
    }
}