pipeline {
    agent {
        kubernetes {
            yaml '''
                apiVersion: v1
                kind: Pod
                spec:
                  nodeSelector:
                    kubernetes.io/arch: amd64
                  containers:
                  - name: maven
                    image: maven:alpine
                    command:
                    - cat
                    tty: true
                  - name: docker
                    image: docker:dind
                    command:
                    - cat
                    tty: true
                '''
        }
    }

    stages {
        stage('Build Docker images') {
            steps {
                dir('react-frontend') {
                    sh "docker info"
                }
            }
        }
    }
}